import h5py
import numpy as np
import cv2
import pyrealsense2 as rs
import os
import shutil
from scipy.spatial.transform import Rotation as R
from tqdm import tqdm

def bridge_to_raw(droid_dir, output_episode_dir):
    # Fix potential path formatting issues
    droid_dir = os.path.normpath(droid_dir)
    os.makedirs(output_episode_dir, exist_ok=True)
    
    h5_path = os.path.join(droid_dir, "trajectory.h5")
    bag_dir = os.path.join(droid_dir, "recordings/Recordings")
    
    with h5py.File(h5_path, 'r') as f:
        # 1. Extract Timestamps and Poses
        # droid now saves relative seconds [0.0, 0.033...] in step_end
        t_rel = f['observation']['timestamp']['control']['step_end'][:]
        
        # 2. Convert DROID Euler (XYZ) to Quaternions (XYZW) for couple.py
        cart_euler = f['action']['cartesian_position'][:]
        xyz = cart_euler[:, :3]
        euler_angles = cart_euler[:, 3:6]
        
        rot_objects = R.from_euler('xyz', euler_angles)
        quats = rot_objects.as_quat() # [qx, qy, qz, qw]
        
        eef_poses = np.hstack([t_rel[:, None], xyz, quats]).astype(np.float32)
        np.save(os.path.join(output_episode_dir, "eef_poses.npy"), eef_poses)

        # 3. Gripper Data
        g_pos = f['action']['gripper_position'][:]
        gripper_data = np.hstack([t_rel[:, None], g_pos[:, None]]).astype(np.float32)
        np.save(os.path.join(output_episode_dir, "gripper_positions.npy"), gripper_data)

        # 4. Handle Video and Pre-saved Timestamps
        bag_files = sorted([f for f in os.listdir(bag_dir) if f.endswith('.bag')])
        
        # Mapping to match your couple.py schema
        cam_mapping = {
            0: {"vid": "hand_color.mp4", "ts_src": "022422070872_rgb_timestamps.npy", "ts_dest": "hand_rgb_timestamps.npy"},
            1: {"vid": "front_color.mp4", "ts_src": "135622077246_rgb_timestamps.npy", "ts_dest": "front_rgb_timestamps.npy"}
        }
        
        for i, bag in enumerate(bag_files):
            if i not in cam_mapping: continue
            
            # --- Move Timestamps (Already generated by your new RealSenseCamera class) ---
            src_ts = os.path.join(bag_dir, cam_mapping[i]["ts_src"])
            dest_ts = os.path.join(output_episode_dir, cam_mapping[i]["ts_dest"])
            if os.path.exists(src_ts):
                shutil.copy(src_ts, dest_ts)
                print(f"[*] Copied pre-saved timestamps: {cam_mapping[i]['ts_dest']}")

            # --- Extract Video from Bag ---
            bag_path = os.path.join(bag_dir, bag)
            pipeline = rs.pipeline()
            config = rs.config()
            rs.config.enable_device_from_file(config, bag_path, False)
            profile = pipeline.start(config)
            playback = rs.playback(profile.get_device())
            playback.set_real_time(False)

            frames = []
            try:
                while True:
                    fs = pipeline.wait_for_frames(2000)
                    color = fs.get_color_frame()
                    if not color: break
                    img = np.asanyarray(color.get_data())
                    frames.append(cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
            except RuntimeError: pass
            finally: pipeline.stop()

            if frames:
                h, w = frames[0].shape[:2]
                out_v = os.path.join(output_episode_dir, cam_mapping[i]["vid"])
                vw = cv2.VideoWriter(out_v, cv2.VideoWriter_fourcc(*'mp4v'), 30, (w, h))
                for frame in frames: vw.write(frame)
                vw.release()

    print(f"[*] Success: Episode 101 raw data generated in {output_episode_dir}")

if __name__ == "__main__":
    bridge_to_raw(
        "/home/robot/droid/data/success/2026-01-20/Tue_Jan_20_14:23:01_2026/", 
        "/home/robot/vla_data/raw/101"
    )